### ISSUE TITLE
Connecting to ADFS

### ISSUE THREAD

**Issue by 1605200517** [Versent/saml2aws#283]
As it seems, there are some configuration possibilities to login to ADFS: ADFS either ADFS2 and there are also sub-options which I do not know.

A couple of configuration ways I consider default do not work (login fails). That is, ADFS and ADFS2 with "saml/Auto".

```
Authenticating as xxxxx...
Response did not contain a valid SAML assertion
Please check your username and password is correct

```
All I do know is that we have ADFS2016 and login works via UI. How to find out/what to ask the system administrator to know what options are correct?

**Comment by GavL89** [comment]
We are seeing this too, it worked on our previous ADFS2012 farm but on the 2019 farm we see this exception in our logs of ADFS:

Exception details: 
Microsoft.IdentityServer.Web.InvalidRequestException: Duplicate post parameter \"UserName\".
   at Microsoft.IdentityServer.Web.HttpContextUtility.ParsePostBodyCore(String postBody, Boolean caseSensitiveKey, List`1 secureKeysList)
   at Microsoft.IdentityServer.Web.UI.PageBase..ctor(WrappedHttpListenerContext httpListenerContext, IList`1 customCulture, RelyingParty relyingParty)
   at Microsoft.IdentityServer.Web.UI.AuthenticationPageBase..ctor(WrappedHttpListenerContext context, ReadOnlyCollection`1 options, IAuthenticationHandler selectedOption, Boolean otherOptions, Boolean renderAllOptionsExplicitly, Boolean isSecondStageAuthentication, Boolean requestUserInteraction, String username, Int32[] customLocales, RelyingParty relyingParty)
   at Microsoft.IdentityServer.Web.UI.ErrorPage..ctor(WrappedHttpListenerContext context, Exception exception, Boolean isSecondStageAuthentication, Boolean requestUserInteraction, String username, ReadOnlyCollection`1 options, IAuthenticationHandler selectedOption, Boolean otherOptions, RelyingParty relyingParty)
   at Microsoft.IdentityServer.Web.UI.ErrorPage.WriteErrorPage(WrappedHttpListenerContext context, Exception exception, Boolean isSecondStageAuthentication, Boolean requestUserInteraction, String username, ReadOnlyCollection`1 options, IAuthenticationHandler selectedOption, Boolean otherOptions, RelyingParty relyingParty)
