### ISSUE TITLE
saml2aws: panic: runtime error: slice bounds out of range [117:91]

### ISSUE THREAD

**Issue by jrp0783** [Versent/saml2aws#436]
i am running saml2aws on ubuntu,, I am getting the following error.

 saml2aws
panic: runtime error: slice bounds out of range [117:91]

goroutine 1 [running]:
github.com/aulanov/go%2edbus.sessionBusPlatform(0xb53b06, 0x18, 0x0)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn_other.go:26 +0x1e9
github.com/aulanov/go%2edbus.SessionBusPrivate(0xc000161de8, 0x7f23d4f4e6d0, 0x0)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:99 +0x5d
github.com/aulanov/go%2edbus.SessionBus(0x0, 0x0, 0x0)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:76 +0xeb
github.com/99designs/keyring.init.1()
        /Users/markw/Code/go/pkg/mod/github.com/99designs/keyring@v0.0.0-20190110203331-82da6802f65f/kwallet.go:18 +0x26

**Comment by mattpull** [comment]
We found removing package dbus-x11 fixed this in WSL ubuntu 1804

**Comment by 1davidmichael** [comment]
> 
> 
> We were getting message:
> 
> > $ ./saml2aws
> > panic: runtime error: slice bounds out of range [308:282]
> > goroutine 1 [running]:
> > github.com/aulanov/go%2edbus.sessionBusPlatform(0xb2941e, 0x18, 0x0)
> > /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn_other.go:26 +0x1e9
> > github.com/aulanov/go%2edbus.SessionBusPrivate(0xd0, 0xabdb00, 0x760f498ce30b6501)
> > /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:99 +0xa7
> > github.com/aulanov/go%2edbus.SessionBus(0x0, 0x0, 0x0)
> > /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:76 +0xae
> > github.com/99designs/keyring.init.1()
> > /Users/markw/Code/go/pkg/mod/github.com/99designs/keyring@v0.0.0-20190110203331-82da6802f65f/kwallet.go:18 +0x26
> 
> We found removing package dbus-x11 fixed this in WSL ubuntu 1804. Hope that helps debug. This was on the latest build 2.24.0

Thanks, this fixed it for me as well.

**Comment by douglasreis** [comment]
I'm using WSL Ubuntu 20.04 and having the same issue with the DBus. It seems DBus needs a machine id generated at `/etc/mahine-id` to work. Usually this value is generated at distribution installation time but the default distribution used in WSL doesn't seem doing it.
So, running the command `sudo systemd-machine-id-setup` generated the machine id and `saml2aws` is now working fine for me.

**Comment by FrancescoKa** [comment]
I Had the same problem, on WSL Ubunto 20.04 (upgrated from WSL 18.04)
Didn't work running the command sudo systemd-machine-id-setup generated
But worked after having removed  dbus-x11
Thanks
