### ISSUE TITLE
startup saml2aws error

### ISSUE THREAD

**Issue by MySSoN** [Versent/saml2aws#506]
saml2aws login
panic: runtime error: slice bounds out of range [121:95]

goroutine 1 [running]:
github.com/aulanov/go%2edbus.sessionBusPlatform(0xb53b06, 0x18, 0x0)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn_other.go:26 +0x1e9
github.com/aulanov/go%2edbus.SessionBusPrivate(0xc00014bde8, 0x7fc2d1956008, 0x0)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:99 +0x5d
github.com/aulanov/go%2edbus.SessionBus(0x0, 0x0, 0x0)
        /Users/markw/Code/go/pkg/mod/github.com/aulanov/go.dbus@v0.0.0-20150729231527-25c3068a42a0/conn.go:76 +0xeb
github.com/99designs/keyring.init.1()
        /Users/markw/Code/go/pkg/mod/github.com/99designs/keyring@v0.0.0-20190110203331-82da6802f65f/kwallet.go:18 +0x26

**Comment by merkinbob** [comment]
I had same issue

See #436 

I was using WSL Ubuntu
`sudo apt-get purge --auto-remove dbus-x11` worked for me

I think this can be closed as duplicate in favor of #436

**Comment by kleintech** [comment]
This also fixed it for me on WSL v2 Ubuntu 20.04

**Comment by jumble** [comment]
For visibility- just hit this issue, but the above fix worked for me. Thanks!
