### ISSUE TITLE
SIGSEGV when running builds created after goreleaser change

### ISSUE THREAD

**Issue by oshaughnessy** [Versent/saml2aws#623]
Starting with 2.28.1, I get SIGSEGV when I run the Linux amd64 build release (under CentOS 7.7) and the Windows build release. Makes me think it must have something to do with #614.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5ed0ea]

goroutine 1 [running]:
net/url.(*URL).String(0x0, 0xba6c2c, 0x6)
       net/url/url.go:813 +0x4a
github.com/versent/saml2aws/v2/pkg/page.NewFormFromDocument(0xc0002feec0, 0xba55ea, 0x4, 0xac3280, 0xc000140400, 0x1)
       github.com/versent/saml2aws/v2/pkg/page/form.go:58 +0x28f
github.com/versent/saml2aws/v2/pkg/provider/pingfed.(*Client).handleLogin(0xc000275700, 0xd06540, 0xc0002838c0, 0xc0002feec0, 0x0, 0x0, 0x2000107, 0x0, 0xffffffffffffffff)
       github.com/versent/saml2aws/v2/pkg/provider/pingfed/pingfed.go:132 +0xaa
github.com/versent/saml2aws/v2/pkg/provider/pingfed.(*Client).follow(0xc000275700, 0xd06540, 0xc0002838c0, 0xc0000e8f00, 0xac3280, 0xc000140400, 0xd06540, 0xc0002838c0)
       github.com/versent/saml2aws/v2/pkg/provider/pingfed/pingfed.go:119 +0x2cc
github.com/versent/saml2aws/v2/pkg/provider/pingfed.(*Client).Authenticate(0xc000275700, 0xc000140400, 0x0, 0x0, 0x0, 0xc00024e8c0)
       github.com/versent/saml2aws/v2/pkg/provider/pingfed/pingfed.go:63 +0x21b
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.ListRoles(0xc00019ff40, 0xbaaf0e, 0xa)
       github.com/versent/saml2aws/v2/cmd/saml2aws/commands/list_roles.go:44 +0x319
main.main()
       command-line-arguments/main.go:178 +0x42ea
```

I would try building locally, but I get a compilation error including bearsh/hid@v1.3.0.

**Comment by wolfeidau** [comment]
@oshaughnessy I did a bunch of changes for linting issues in https://github.com/Versent/saml2aws/pull/610, this maybe related. 

We use this provider a lot so it maybe a branch / edge case we don't cover hit.
